# Generated by Django 4.1.7 on 2023-02-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='county_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
